# Generated by Django 6.0.1 on 2026-01-09 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='core.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodotto',
            name='descrizione',
            field=models.TextField(blank=True, help_text='Descrizione del prodotto'),
        ),
    ]
