# Generated by Django 6.0.1 on 2026-01-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prodotto_categoria_prodotto_descrizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Prezzo in euro', max_digits=8),
            preserve_default=False,
        ),
    ]
