# Generated by Django 6.0.1 on 2026-01-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prodotto_prezzo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descrizione',
        ),
        migrations.RemoveField(
            model_name='fornitore',
            name='indirizzo',
        ),
        migrations.RemoveField(
            model_name='fornitore',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='fornitore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='fornitore',
        ),
        migrations.AddField(
            model_name='prodotto',
            name='codice',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodotto',
            name='fornitori',
            field=models.ManyToManyField(blank=True, related_name='prodotti', to='core.fornitore'),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='ragione_sociale',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='descrizione',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='quantita',
            field=models.PositiveIntegerField(),
        ),
    ]
