# Generated by Django 6.0.1 on 2026-01-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_categoria_options_remove_categoria_descrizione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='codice',
            field=models.CharField(max_length=50),
        ),
    ]
