# Generated by Django 6.0.1 on 2026-01-09 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_prodotto_codice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='attivo',
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='quantita',
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='codice',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
