# Generated by Django 6.0.1 on 2026-01-09 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_prodotto_attivo_remove_prodotto_quantita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='fornitori',
        ),
        migrations.AddField(
            model_name='fornitore',
            name='indirizzo',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornitore',
            name='prodotti',
            field=models.ManyToManyField(blank=True, related_name='fornitori', to='core.prodotto'),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='telefono',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodotto',
            name='quantita',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prodotti', to='core.categoria'),
        ),
    ]
