# Generated by Django 6.0.1 on 2026-01-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_prodotto_fornitori_fornitore_indirizzo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorie'},
        ),
    ]
