# Generated by Django 6.0.1 on 2026-01-11 12:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_categoria_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(core.models.default_categoria), related_name='prodotti', to='core.categoria'),
        ),
    ]
