# Generated by Django 6.0.1 on 2026-01-20 11:32

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ordineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fornitore',
            name='utente',
            field=models.ForeignKey(blank=True, limit_choices_to={'ruolo': 'FORNITORE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorie_fornite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='attivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='fornitore',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(core.models.default_fornitore), related_name='prodotti_forniti', to='core.fornitore'),
        ),
    ]
