# Generated by Django 6.0.1 on 2026-01-20 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fornitore_utente_prodotto_attivo_prodotto_fornitore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordine',
            options={'ordering': ['-data_ordine']},
        ),
        migrations.RenameField(
            model_name='ordine',
            old_name='data',
            new_name='data_ordine',
        ),
        migrations.AddField(
            model_name='ordine',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordine',
            name='stato',
            field=models.CharField(choices=[('PEN', 'In attesa'), ('CON', 'Confermato'), ('SPE', 'Spedito'), ('DEL', 'Consegnato'), ('ANN', 'Annullato')], default='PEN', max_length=3),
        ),
        migrations.CreateModel(
            name='OrdineDettaglio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField()),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettagli', to='core.ordine')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.prodotto')),
            ],
        ),
        migrations.DeleteModel(
            name='OrdineItem',
        ),
    ]
