# Generated by Django 6.0.1 on 2026-01-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_ruolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ruolo',
            field=models.CharField(choices=[('CLI', 'Cliente'), ('FOR', 'Fornitore'), ('ADM', 'Amministratore')], default='CLI', max_length=3),
        ),
    ]
